"""fix forecast table base import

Revision ID: c00d381dde97
Revises: a4ad463a7ddb
Create Date: 2026-06-30 10:39:48.236660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00d381dde97'
down_revision: Union[str, Sequence[str], None] = 'a4ad463a7ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'forecasts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forecasts', type_='foreignkey')
    # ### end Alembic commands ###
