import { useQuery } from '@tanstack/react-query';
import { TrendingDown, TrendingUp, DollarSign } from 'lucide-react';
import MetricCard from '../components/MetricCard';
import ForecastChart from '../components/ForecastChart';
import LoadingSkeleton from '../components/LoadingSkeleton';
import { getForecast } from '../api/ml';

// BUG FIXED: this entire page was 100% hardcoded fake data — it never called
// the backend's /api/ml/forecast endpoint at all. No matter what your Prophet
// model predicted, the user always saw the same fabricated numbers
// ($48,250 / $5,120 / "Rising"). Now it actually fetches and renders the
// real forecast generated by ml/forecasting.py.

export default function ForecastPage() {
  const { data, isLoading } = useQuery({
    queryKey: ['forecast'],
    queryFn: getForecast,
  });

  const forecastRows = data?.data || [];

  // Reshape backend rows {date, predicted_cost, lower_bound, upper_bound}
  // into the {date, predicted_cost, confidence_bounds:[low,high]} shape
  // ForecastChart expects.
  const chartData = forecastRows.map((row, i) => ({
    date: i === 0 ? 'Today' : row.date,
    predicted_cost: row.predicted_cost,
    confidence_bounds: [row.lower_bound, row.upper_bound],
  }));

  const totalNext30 = forecastRows.reduce((sum, r) => sum + r.predicted_cost, 0);
  const firstCost = forecastRows[0]?.predicted_cost || 0;
  const lastCost = forecastRows[forecastRows.length - 1]?.predicted_cost || 0;
  const trendRising = lastCost > firstCost;
  const trendPercent = firstCost > 0 ? Math.abs(((lastCost - firstCost) / firstCost) * 100).toFixed(1) : 0;

  if (isLoading) {
    return (
      <div className="space-y-6">
        <LoadingSkeleton className="h-96" />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[1, 2, 3].map(i => <LoadingSkeleton key={i} className="h-28" />)}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in max-w-6xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-text-primary">Spend Forecast</h1>
        <p className="text-text-muted mt-1">AI-driven cost projections with confidence intervals (Prophet model).</p>
      </div>

      {forecastRows.length === 0 ? (
        <div className="bg-bg-secondary border border-border rounded-xl p-8 text-center">
          <p className="text-text-primary font-medium mb-2">No forecast data yet</p>
          <p className="text-text-muted text-sm">
            Run a scan from the Dashboard first — the forecast needs at least 30 days of cost history to generate predictions.
          </p>
        </div>
      ) : (
        <>
          <div className="bg-bg-secondary border border-border p-6 rounded-xl shadow-sm">
            <ForecastChart data={chartData} />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
            <MetricCard
              label="Predicted Next 30 Days"
              value={`$${totalNext30.toLocaleString(undefined, { maximumFractionDigits: 0 })}`}
              icon={DollarSign}
            />
            <MetricCard
              label="Cost Trend"
              value={trendRising ? 'Rising' : 'Falling'}
              change={trendPercent}
              changeDirection={trendRising ? 'up' : 'down'}
              icon={trendRising ? TrendingUp : TrendingDown}
            />
            <MetricCard
              label="Forecast Range"
              value={`${forecastRows.length} days`}
              icon={TrendingDown}
            />
          </div>
        </>
      )}
    </div>
  );
}
